version: '2'
services:
  orderer0.example.com:
    container_name: orderer0.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6050
        - PBFT_LISTEN_PORT=6070
        - PBFT_NODE_ID=0
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6070
        - SESTUFF_NODE_ID=0
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer0
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6050:6050
      - 6070:6070

  orderer1.example.com:
    container_name: orderer1.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6051
        - PBFT_LISTEN_PORT=6071
        - PBFT_NODE_ID=1
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6071
        - SESTUFF_NODE_ID=1
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer1
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6051:6051
      - 6071:6071

  orderer2.example.com:
    container_name: orderer2.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6052
        - PBFT_LISTEN_PORT=6072
        - PBFT_NODE_ID=2
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6072
        - SESTUFF_NODE_ID=2
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer2
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6052:6052
      - 6072:6072

  orderer3.example.com:
    container_name: orderer3.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6053
        - PBFT_LISTEN_PORT=6073
        - PBFT_NODE_ID=3
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6073
        - SESTUFF_NODE_ID=3
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer3
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6053:6053
      - 6073:6073

  orderer4.example.com:
    container_name: orderer4.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6054
        - PBFT_LISTEN_PORT=6074
        - PBFT_NODE_ID=4
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6074
        - SESTUFF_NODE_ID=4
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer4
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6054:6054
      - 6074:6074

  orderer5.example.com:
    container_name: orderer5.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6055
        - PBFT_LISTEN_PORT=6075
        - PBFT_NODE_ID=5
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6075
        - SESTUFF_NODE_ID=5
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer5
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6055:6055
      - 6075:6075

  orderer6.example.com:
    container_name: orderer6.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6056
        - PBFT_LISTEN_PORT=6076
        - PBFT_NODE_ID=6
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6076
        - SESTUFF_NODE_ID=6
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer6.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer6.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer6
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6056:6056
      - 6076:6076

  orderer7.example.com:
    container_name: orderer7.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6057
        - PBFT_LISTEN_PORT=6077
        - PBFT_NODE_ID=7
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6077
        - SESTUFF_NODE_ID=7
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer7.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer7.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer7
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6057:6057
      - 6077:6077

  orderer8.example.com:
    container_name: orderer8.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6058
        - PBFT_LISTEN_PORT=6078
        - PBFT_NODE_ID=8
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6078
        - SESTUFF_NODE_ID=8
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer8.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer8.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer8
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6058:6058
      - 6078:6078

  orderer9.example.com:
    container_name: orderer9.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6059
        - PBFT_LISTEN_PORT=6079
        - PBFT_NODE_ID=9
        - PBFT_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
        - SESTUFF_LISTEN_PORT=6079
        - SESTUFF_NODE_ID=9
        - SESTUFF_NODE_TABLE=http://orderer0.example.com:6070;http://orderer1.example.com:6071;http://orderer2.example.com:6072;http://orderer3.example.com:6073;http://orderer4.example.com:6074;http://orderer5.example.com:6075;http://orderer6.example.com:6076;http://orderer7.example.com:6077;http://orderer8.example.com:6078;http://orderer9.example.com:6079
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer9.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer9.example.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer9
        - ../../client/reputation:/opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 6059:6059
      - 6079:6079

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ../production/org1:/var/hyperledger/production/peer0
    ports:
      - 7051:7051

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ../production/org1:/var/hyperledger/production/peer1

    ports:
      - 8051:8051