# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  edge:

services:
  couchdb0_1:
    container_name: couchdb0_1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=666666
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - edge

  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
    depends_on:
      - couchdb0_1

  couchdb1_1:
    container_name: couchdb1_1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=666666
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - edge

  peer1.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
    depends_on:
      - couchdb1_1

  # couchdb2_1:
  #   container_name: couchdb2_1
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=666666
  #   # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
  #   # for example map it to utilize Fauxton User Interface in dev environments.
  #   ports:
  #     - "9984:5984"
  #   networks:
  #     - edge

  # peer2.org1.example.com:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2_1:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
  #   depends_on:
  #     - couchdb2_1

  # couchdb0_2:
  #   container_name: couchdb0_2
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=666666
  #   # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
  #   # for example map it to utilize Fauxton User Interface in dev environments.
  #   ports:
  #     - "7984:5984"
  #   networks:
  #     - edge

  # peer0.org2.example.com:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_2:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
  #   depends_on:
  #     - couchdb0_2

  # couchdb1_2:
  #   container_name: couchdb1_2
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=666666
  #   # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
  #   # for example map it to utilize Fauxton User Interface in dev environments.
  #   ports:
  #     - "8984:5984"
  #   networks:
  #     - edge

  # peer1.org2.example.com:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_2:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
  #   depends_on:
  #     - couchdb1_2

  # couchdb2_2:
  #   container_name: couchdb2_2
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=666666
  #   # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
  #   # for example map it to utilize Fauxton User Interface in dev environments.
  #   ports:
  #     - "10984:5984"
  #   networks:
  #     - edge

  # peer2.org2.example.com:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2_2:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=666666
  #   depends_on:
  #     - couchdb2_2
